influxdb:
  image: influxdb:alpine
  ports:
    - 8083:8083
    - 8086:8086

fuzz:
  image: quay.io/gaker/fuzz
  ports:
    - "8000:8000"
  links:
    - influxdb
  environment:
    INFLUX_DB_NAME: 'monitor'
    AUTH_TOKEN: abc123


grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
